### ISSUE TITLE
Include filename on AnimadeDiff Script node

### ISSUE THREAD

**Issue by HaydenReeve** [jags111/efficiency-nodes-comfyui#14]
AnimateDiff Evolved has a filename input on its model which would be super handy to be able to configure in Efficiency.

It'd probably be worth looking at porting that one over to the script node. As a user, I'd be very pleased to be able to tell it where to output its images rather than letting it hardcode itself into the `output/` directory.

i.e.: `output/%date%/%date%_%model` (typically done though the save node)

**Comment by jags111** [comment]
For sure will do same and update this node. Thanks !

**Comment by dnl13** [comment]
to discuss:
imho 
this scrip only should contain Kosinkadinks "AnimateDiff Loader" because this is the only logical point to hook into the model.
Also this script should get all the same inputs like Kosinkadink "AnimateDiff Loader". 
Kosinkadink added a ton of nice extra nodes like nodes to add the motion loras etc., which is missing in this script completly. 
Also in the favor of node based editing, the user should add a video combine node by himself or this video combine node should be added to efficiency-nodes for faster acces instead of adding Kosinkadink VideoHelperSuite. 
Also thinking of maintaining this repo, this script is nice to have but is it realy mandetory ?

**Comment by jags111** [comment]
very right and so many changes daily in AD repo which i am very much aware of and it is fast evolving. To keep track of it and keep updating it is a mess and wont help much. Better to drop this node and remove unless something different is there. Thanks for the clarifications. I think any node which is duplicated is no purpose at all.

**Comment by jags111** [comment]
I think we will need to revise this node totally and for time being will keep it on hold as ANIMATE DIFF is going through a lot of changes
