### ISSUE TITLE
Highres-Fix breaks on load.

### ISSUE THREAD

**Issue by Piscabo** [jags111/efficiency-nodes-comfyui#147]
Every time  re-load the workflow the node reset to 'NaN' when set to 'both' does this:

![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/123719842/6c3aea49-f176-404f-8e9a-49cd93674e40)

**Comment by jags111** [comment]
here is the test with the latest HIRES script workflow.. I am only not sure with the pixel space upscale and may need to relook at code for same.. But it is working without nay issues like shown;  Any how if pixel upscale is needed better to sperate it to another node rather than run it in sampler like this as it may cause some latent move.
<img width="1089" alt="2024-04-06_10-05-01" src="https://github.com/jags111/efficiency-nodes-comfyui/assets/5968619/fbe11654-d522-4c63-872c-072255e00c83">

**Comment by LiJT** [comment]
I have the same issue too! The highres-fix will reset to its "NaN" value when reloading the workflow!
![image](https://github.com/jags111/efficiency-nodes-comfyui/assets/11270197/24d49f95-305d-4a3c-8751-d227fbcbc267)

this is my workflow attached. 
[Playground v2.json](https://github.com/jags111/efficiency-nodes-comfyui/files/14978925/Playground.v2.json)

**Comment by Shinihime** [comment]
I fixed it and made a pull request.
If you wanna fix it locally yourself before this fix is merged: [https://github.com/jags111/efficiency-nodes-comfyui/pull/183/files](url)

**Comment by jags111** [comment]
this is resolved.
